# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shinyapp',
            old_name='name',
            new_name='shiny_name',
        ),
        migrations.RenameField(
            model_name='shinyapp',
            old_name='show',
            new_name='shiny_show',
        ),
        migrations.AddField(
            model_name='shinyapp',
            name='shiny_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
