# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160413_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='shinyapp',
            name='shiny_address',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
