# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shinyapp_shiny_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shinyapp',
            name='shiny_address',
            field=models.URLField(default=''),
        ),
    ]
