# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sfnteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfnteam',
            name='affil',
            field=models.CharField(default='CREAF', max_length=200),
        ),
    ]
