# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sfnteam_affil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfnteam',
            name='courtesy',
            field=models.CharField(default='', max_length=200),
        ),
    ]
