# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfnform', '0013_dataupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='metadata_spreadsheet',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
