# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import sfnform.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sfnform', '0016_auto_20160310_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='envdata_file',
            field=models.FileField(default='none', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='metadata_spreadsheet',
            field=models.FileField(upload_to=b'', validators=[sfnform.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='sapflow_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
