# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import sfnform.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sfnform', '0018_auto_20160310_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='envdata_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='sapflow_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='envdata_file',
            field=models.FileField(null=True, upload_to=b'', validators=[sfnform.validators.validate_file_extension_csv]),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='sapflow_file',
            field=models.FileField(null=True, upload_to=b'', validators=[sfnform.validators.validate_file_extension_csv]),
        ),
    ]
