# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import sfnform.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sfnform', '0020_auto_20160405_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='envdata_file',
            field=models.FileField(null=True, upload_to=b'/data/', validators=[sfnform.validators.validate_file_extension_csv]),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='metadata_spreadsheet',
            field=models.FileField(upload_to=b'/data/', validators=[sfnform.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='sapflow_file',
            field=models.FileField(null=True, upload_to=b'/data/', validators=[sfnform.validators.validate_file_extension_csv]),
        ),
    ]
